// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuri8JVoLYN-5JIYhEN_NT3KdvexID3Tg',
    appId: '1:215711687829:web:9b50942eac54926c59679c',
    messagingSenderId: '215711687829',
    projectId: 'buycott-df7fa',
    authDomain: 'buycott-df7fa.firebaseapp.com',
    storageBucket: 'buycott-df7fa.appspot.com',
    measurementId: 'G-BWMNX6FL4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWE7MBEKIP4zNgXMXMw2h8eHgRtS_xOPs',
    appId: '1:215711687829:android:5b6b03b31a5e596b59679c',
    messagingSenderId: '215711687829',
    projectId: 'buycott-df7fa',
    storageBucket: 'buycott-df7fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXrlN94MqmTBj_tqz9P72nxfvAz-IsAig',
    appId: '1:215711687829:ios:c9179b133698913659679c',
    messagingSenderId: '215711687829',
    projectId: 'buycott-df7fa',
    storageBucket: 'buycott-df7fa.appspot.com',
    iosBundleId: 'com.minijini.buycott',
  );
}
