// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Qtn9lfbYw6psS0dlqnejfMLU5aCUAY4',
    appId: '1:967814441197:web:9e15ff5783018a97a104e4',
    messagingSenderId: '967814441197',
    projectId: 'atthattime-22983',
    authDomain: 'atthattime-22983.firebaseapp.com',
    storageBucket: 'atthattime-22983.appspot.com',
    measurementId: 'G-HRFTGNGF1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Jkj59WeMhgm0_1ixtVjIclc0fLrvCdo',
    appId: '1:967814441197:android:9702f79fcc24bb26a104e4',
    messagingSenderId: '967814441197',
    projectId: 'atthattime-22983',
    storageBucket: 'atthattime-22983.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAYzOSLel9guFG8BGQ51WnhyJNcXab4o4',
    appId: '1:967814441197:ios:849685cd54edf936a104e4',
    messagingSenderId: '967814441197',
    projectId: 'atthattime-22983',
    storageBucket: 'atthattime-22983.appspot.com',
    androidClientId: '967814441197-o3p3b67qc8pipu3858uoph36hhobtiu2.apps.googleusercontent.com',
    iosClientId: '967814441197-e1lra78lgc1etfd2n1odndp9tnfrgqam.apps.googleusercontent.com',
    iosBundleId: 'com.goduk.atthattime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAYzOSLel9guFG8BGQ51WnhyJNcXab4o4',
    appId: '1:967814441197:ios:fbb4859bb5d5c63fa104e4',
    messagingSenderId: '967814441197',
    projectId: 'atthattime-22983',
    storageBucket: 'atthattime-22983.appspot.com',
    androidClientId: '967814441197-o3p3b67qc8pipu3858uoph36hhobtiu2.apps.googleusercontent.com',
    iosClientId: '967814441197-3nb4glltq3vkmch6kr5nr23clfjuuqu8.apps.googleusercontent.com',
    iosBundleId: 'com.goduk.atThatTime.RunnerTests',
  );
}
